imports:
    - { resource: 'sources.yml' }
    - { resource: 'protocols.yml' }
    - { resource: 'commands.yml' }

services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    source_manager:
        class: Carbon14\Manager\SourceManager

    protocol_manager:
        class: Carbon14\Manager\ProtocolManager

    command_manager:
        class: Carbon14\Manager\CommandManager

    job_manager:
        class: Carbon14\Manager\JobManager
        arguments:
          - "@source_manager"
